### ISSUE TITLE
PlayersSettingViewController実装

### ISSUE THREAD

**Issue by bati668** [hiromiick/D-Rec#25]
[作る画面]
<img width="306" alt="2018-11-13 13 03 29" src="https://user-images.githubusercontent.com/11172948/48390316-a5305280-e744-11e8-8a7d-ccb051f87fe9.png">

[手順]

1. 以下のコマンドをターミナルで実行
```
cd D-rec(もしD-recのディレクトリにいない場合、cdで移動。今どこにいるかは、lsで確認)
git checkout develop(もし現在develop branchにいなかったら実行。今どこにいるかは、git branchで確認)
git checkout -b"feature/issue#25"
```

2. 以下のfileを作成
PlayersSettingViewController.storyboardを作成
PlayersSettingViewController.swift作成
IBDesinableを使って、PlayersSettingCellView.swiftとPlayersSettingCellView.xibを作成。
PlayersSettingCellViewは、UIViewを継承したクラス。
タップすると、Pickerが出て、選択できるように

**Comment by hiromiick** [comment]
1のターミナルは完了。2の.storyboardを作成はしましたが、その中身の編集だったりを少し電話で会話させてほしいです。
