### ISSUE TITLE
Prayer画面UI実装

### ISSUE THREAD

**Issue by bati668** [hiromiick/D-Rec#42]
- すでに各々のViewControllerはできてるので、Pageで繋げる
- PrayerListCellのデザインが少し変わったので、修正
- DateLabelの横のオレンジのやつはまだつけてないのでそこを、つける
<img width="245" alt="2018-11-23 15 50 28" src="https://user-images.githubusercontent.com/11172948/48931027-8cd7e900-ef37-11e8-8def-ce8345932ddd.png">

- ナビゲーションのとこタップすると、アラートが出てきて、それぞれのボタンを押すと、sortできるように
<img width="387" alt="2018-11-23 15 52 33" src="https://user-images.githubusercontent.com/11172948/48931079-d0325780-ef37-11e8-923a-ccf036006bfb.png">

<img width="164" alt="2018-11-23 15 58 20" src="https://user-images.githubusercontent.com/11172948/48931247-a2014780-ef38-11e8-8a4d-18cfbce0071e.png">

<img width="208" alt="2018-11-23 15 59 14" src="https://user-images.githubusercontent.com/11172948/48931266-bfceac80-ef38-11e8-9872-c2bb0b2d902b.png">

**Comment by hiromiick** [comment]
補足させてください。

Navigation Bar Titleをタップすると、ActionSheet表示。
デフォルトは、On-Goingのみ表示しているが、Completed、Canceled、Pendingを選択して、過去の御祈念項目を表示させることが出来る。但し、「Your Own」「Friends」はすべてのステータスを確認することが可能だが、「Public」は「On-Going」のみを表示させる。

ソートではなく、フィルタリングの機能です。デフォルトでは、御記念項目のステータスが「On-Going」のもののみを表示させているが、NavigationBarの文字の箇所をタップすることで、御記念項目のステータスが「Canceld」や「Completed」のものの表示に切り替えることが出来るというイメージです。

以上、よろしくお願いします
